name: Build on Commit

on:
  push:
    branches:
      - main  # 监听 main 分支的推送，提交到 main 分支时触发

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64  # 选择 x64 架构
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print actual architecture
        run: |
          echo "Running on macOS"
          arch_output=$(uname -m)  # 获取当前机器的架构
          echo "The architecture of the current macOS is: $arch_output"
